BUG#39116948 Unrestricted protocol redirection - postfix
Fix compilation error:
  unused variable 'k_allowed_rest_protocols' [-Werror,-Wunused-const-variable]

Change-Id: I8e729b584380f5ef63eec5c2183164ad30de5eab